/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CacaoFlowOpportunities {
  export type OpportunityStruct = {
    vpcId: string;
    opportunityId: string;
    originator: AddressLike;
    targetRaise: BigNumberish;
    minTicket: BigNumberish;
    expectedReturnBps: BigNumberish;
    tenorDays: BigNumberish;
    fundingDeadline: BigNumberish;
    raisedAmount: BigNumberish;
    settleAmount: BigNumberish;
    status: BigNumberish;
  };

  export type OpportunityStructOutput = [
    vpcId: string,
    opportunityId: string,
    originator: string,
    targetRaise: bigint,
    minTicket: bigint,
    expectedReturnBps: bigint,
    tenorDays: bigint,
    fundingDeadline: bigint,
    raisedAmount: bigint,
    settleAmount: bigint,
    status: bigint
  ] & {
    vpcId: string;
    opportunityId: string;
    originator: string;
    targetRaise: bigint;
    minTicket: bigint;
    expectedReturnBps: bigint;
    tenorDays: bigint;
    fundingDeadline: bigint;
    raisedAmount: bigint;
    settleAmount: bigint;
    status: bigint;
  };

  export type PositionStruct = {
    opportunityId: BigNumberish;
    investor: AddressLike;
    amount: BigNumberish;
    claimed: boolean;
  };

  export type PositionStructOutput = [
    opportunityId: bigint,
    investor: string,
    amount: bigint,
    claimed: boolean
  ] & {
    opportunityId: bigint;
    investor: string;
    amount: bigint;
    claimed: boolean;
  };
}

export interface CacaoFlowOpportunitiesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "PLATFORM_FEE_BPS"
      | "activateOpportunity"
      | "cancelOpportunity"
      | "claimRefund"
      | "claimRepayment"
      | "createOpportunity"
      | "emergencyWithdraw"
      | "feeRecipient"
      | "getInvestorPositions"
      | "getOpportunity"
      | "getOpportunityPositions"
      | "getPosition"
      | "invest"
      | "investorPositions"
      | "markDefaulted"
      | "markRepaid"
      | "opportunities"
      | "opportunityCount"
      | "opportunityPositions"
      | "owner"
      | "positionCount"
      | "positions"
      | "publishOpportunity"
      | "renounceOwnership"
      | "setFeeRecipient"
      | "transferOwnership"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InvestmentMade"
      | "InvestmentRefunded"
      | "OpportunityCancelled"
      | "OpportunityFunded"
      | "OpportunityPublished"
      | "OpportunitySettled"
      | "OwnershipTransferred"
      | "RepaymentClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activateOpportunity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOpportunity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRepayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createOpportunity",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestorPositions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOpportunity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOpportunityPositions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "invest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "investorPositions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markDefaulted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markRepaid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "opportunities",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "opportunityCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "opportunityPositions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "publishOpportunity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateOpportunity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOpportunity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOpportunity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvestorPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOpportunity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOpportunityPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "investorPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markDefaulted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markRepaid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "opportunities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "opportunityCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "opportunityPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishOpportunity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace InvestmentMadeEvent {
  export type InputTuple = [
    opportunityId: BigNumberish,
    positionId: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    opportunityId: bigint,
    positionId: bigint,
    investor: string,
    amount: bigint
  ];
  export interface OutputObject {
    opportunityId: bigint;
    positionId: bigint;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentRefundedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    investor: string,
    amount: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OpportunityCancelledEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OpportunityFundedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OpportunityPublishedEvent {
  export type InputTuple = [
    id: BigNumberish,
    vpcId: string,
    opportunityId: string,
    originator: AddressLike,
    targetRaise: BigNumberish,
    expectedReturnBps: BigNumberish,
    tenorDays: BigNumberish,
    fundingDeadline: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    vpcId: string,
    opportunityId: string,
    originator: string,
    targetRaise: bigint,
    expectedReturnBps: bigint,
    tenorDays: bigint,
    fundingDeadline: bigint
  ];
  export interface OutputObject {
    id: bigint;
    vpcId: string;
    opportunityId: string;
    originator: string;
    targetRaise: bigint;
    expectedReturnBps: bigint;
    tenorDays: bigint;
    fundingDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OpportunitySettledEvent {
  export type InputTuple = [id: BigNumberish, settleAmount: BigNumberish];
  export type OutputTuple = [id: bigint, settleAmount: bigint];
  export interface OutputObject {
    id: bigint;
    settleAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaymentClaimedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    investor: AddressLike,
    principal: BigNumberish,
    returnAmount: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    investor: string,
    principal: bigint,
    returnAmount: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    investor: string;
    principal: bigint;
    returnAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CacaoFlowOpportunities extends BaseContract {
  connect(runner?: ContractRunner | null): CacaoFlowOpportunities;
  waitForDeployment(): Promise<this>;

  interface: CacaoFlowOpportunitiesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  activateOpportunity: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelOpportunity: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<
    [positionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRepayment: TypedContractMethod<
    [positionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createOpportunity: TypedContractMethod<
    [
      vpcId: string,
      opportunityId: string,
      targetRaise: BigNumberish,
      minTicket: BigNumberish,
      expectedReturnBps: BigNumberish,
      tenorDays: BigNumberish,
      fundingDeadlineDays: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getInvestorPositions: TypedContractMethod<
    [investor: AddressLike],
    [bigint[]],
    "view"
  >;

  getOpportunity: TypedContractMethod<
    [id: BigNumberish],
    [CacaoFlowOpportunities.OpportunityStructOutput],
    "view"
  >;

  getOpportunityPositions: TypedContractMethod<
    [id: BigNumberish],
    [bigint[]],
    "view"
  >;

  getPosition: TypedContractMethod<
    [positionId: BigNumberish],
    [CacaoFlowOpportunities.PositionStructOutput],
    "view"
  >;

  invest: TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  investorPositions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  markDefaulted: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  markRepaid: TypedContractMethod<
    [id: BigNumberish, settleAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  opportunities: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        vpcId: string;
        opportunityId: string;
        originator: string;
        targetRaise: bigint;
        minTicket: bigint;
        expectedReturnBps: bigint;
        tenorDays: bigint;
        fundingDeadline: bigint;
        raisedAmount: bigint;
        settleAmount: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  opportunityCount: TypedContractMethod<[], [bigint], "view">;

  opportunityPositions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  positionCount: TypedContractMethod<[], [bigint], "view">;

  positions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean] & {
        opportunityId: bigint;
        investor: string;
        amount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  publishOpportunity: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeeRecipient: TypedContractMethod<
    [_feeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activateOpportunity"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelOpportunity"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[positionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRepayment"
  ): TypedContractMethod<[positionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createOpportunity"
  ): TypedContractMethod<
    [
      vpcId: string,
      opportunityId: string,
      targetRaise: BigNumberish,
      minTicket: BigNumberish,
      expectedReturnBps: BigNumberish,
      tenorDays: BigNumberish,
      fundingDeadlineDays: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getInvestorPositions"
  ): TypedContractMethod<[investor: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getOpportunity"
  ): TypedContractMethod<
    [id: BigNumberish],
    [CacaoFlowOpportunities.OpportunityStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOpportunityPositions"
  ): TypedContractMethod<[id: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [CacaoFlowOpportunities.PositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "invest"
  ): TypedContractMethod<
    [id: BigNumberish, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "investorPositions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "markDefaulted"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markRepaid"
  ): TypedContractMethod<
    [id: BigNumberish, settleAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "opportunities"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        vpcId: string;
        opportunityId: string;
        originator: string;
        targetRaise: bigint;
        minTicket: bigint;
        expectedReturnBps: bigint;
        tenorDays: bigint;
        fundingDeadline: bigint;
        raisedAmount: bigint;
        settleAmount: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "opportunityCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "opportunityPositions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "positions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean] & {
        opportunityId: bigint;
        investor: string;
        amount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "publishOpportunity"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[_feeRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "InvestmentMade"
  ): TypedContractEvent<
    InvestmentMadeEvent.InputTuple,
    InvestmentMadeEvent.OutputTuple,
    InvestmentMadeEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentRefunded"
  ): TypedContractEvent<
    InvestmentRefundedEvent.InputTuple,
    InvestmentRefundedEvent.OutputTuple,
    InvestmentRefundedEvent.OutputObject
  >;
  getEvent(
    key: "OpportunityCancelled"
  ): TypedContractEvent<
    OpportunityCancelledEvent.InputTuple,
    OpportunityCancelledEvent.OutputTuple,
    OpportunityCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OpportunityFunded"
  ): TypedContractEvent<
    OpportunityFundedEvent.InputTuple,
    OpportunityFundedEvent.OutputTuple,
    OpportunityFundedEvent.OutputObject
  >;
  getEvent(
    key: "OpportunityPublished"
  ): TypedContractEvent<
    OpportunityPublishedEvent.InputTuple,
    OpportunityPublishedEvent.OutputTuple,
    OpportunityPublishedEvent.OutputObject
  >;
  getEvent(
    key: "OpportunitySettled"
  ): TypedContractEvent<
    OpportunitySettledEvent.InputTuple,
    OpportunitySettledEvent.OutputTuple,
    OpportunitySettledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RepaymentClaimed"
  ): TypedContractEvent<
    RepaymentClaimedEvent.InputTuple,
    RepaymentClaimedEvent.OutputTuple,
    RepaymentClaimedEvent.OutputObject
  >;

  filters: {
    "InvestmentMade(uint256,uint256,address,uint256)": TypedContractEvent<
      InvestmentMadeEvent.InputTuple,
      InvestmentMadeEvent.OutputTuple,
      InvestmentMadeEvent.OutputObject
    >;
    InvestmentMade: TypedContractEvent<
      InvestmentMadeEvent.InputTuple,
      InvestmentMadeEvent.OutputTuple,
      InvestmentMadeEvent.OutputObject
    >;

    "InvestmentRefunded(uint256,address,uint256)": TypedContractEvent<
      InvestmentRefundedEvent.InputTuple,
      InvestmentRefundedEvent.OutputTuple,
      InvestmentRefundedEvent.OutputObject
    >;
    InvestmentRefunded: TypedContractEvent<
      InvestmentRefundedEvent.InputTuple,
      InvestmentRefundedEvent.OutputTuple,
      InvestmentRefundedEvent.OutputObject
    >;

    "OpportunityCancelled(uint256)": TypedContractEvent<
      OpportunityCancelledEvent.InputTuple,
      OpportunityCancelledEvent.OutputTuple,
      OpportunityCancelledEvent.OutputObject
    >;
    OpportunityCancelled: TypedContractEvent<
      OpportunityCancelledEvent.InputTuple,
      OpportunityCancelledEvent.OutputTuple,
      OpportunityCancelledEvent.OutputObject
    >;

    "OpportunityFunded(uint256)": TypedContractEvent<
      OpportunityFundedEvent.InputTuple,
      OpportunityFundedEvent.OutputTuple,
      OpportunityFundedEvent.OutputObject
    >;
    OpportunityFunded: TypedContractEvent<
      OpportunityFundedEvent.InputTuple,
      OpportunityFundedEvent.OutputTuple,
      OpportunityFundedEvent.OutputObject
    >;

    "OpportunityPublished(uint256,string,string,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      OpportunityPublishedEvent.InputTuple,
      OpportunityPublishedEvent.OutputTuple,
      OpportunityPublishedEvent.OutputObject
    >;
    OpportunityPublished: TypedContractEvent<
      OpportunityPublishedEvent.InputTuple,
      OpportunityPublishedEvent.OutputTuple,
      OpportunityPublishedEvent.OutputObject
    >;

    "OpportunitySettled(uint256,uint256)": TypedContractEvent<
      OpportunitySettledEvent.InputTuple,
      OpportunitySettledEvent.OutputTuple,
      OpportunitySettledEvent.OutputObject
    >;
    OpportunitySettled: TypedContractEvent<
      OpportunitySettledEvent.InputTuple,
      OpportunitySettledEvent.OutputTuple,
      OpportunitySettledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RepaymentClaimed(uint256,address,uint256,uint256)": TypedContractEvent<
      RepaymentClaimedEvent.InputTuple,
      RepaymentClaimedEvent.OutputTuple,
      RepaymentClaimedEvent.OutputObject
    >;
    RepaymentClaimed: TypedContractEvent<
      RepaymentClaimedEvent.InputTuple,
      RepaymentClaimedEvent.OutputTuple,
      RepaymentClaimedEvent.OutputObject
    >;
  };
}
